name: Create release packages

on:
  release:
    types: [published]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build releases
        run: make release
      - name: List files
        run: ls release/*
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: |
            release/*
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: "release/*"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
